# Generated by Django 4.1.4 on 2022-12-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_bot', '0002_user_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.CharField(default=None, max_length=50, unique=True, verbose_name='Id чата'),
        ),
    ]
