# Generated by Django 4.1.4 on 2022-12-09 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon_bot', '0003_alter_user_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='salon',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='salon_bot.salon', verbose_name='Салон'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='salon_bot.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='specialist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='salon_bot.specialist', verbose_name='Мастер'),
        ),
    ]
