# Generated by Django 4.1.4 on 2022-12-09 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon_bot', '0005_alter_purchase_salon_alter_purchase_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salon_bot.salon', verbose_name='Салон'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salon_bot.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salon_bot.specialist', verbose_name='Мастер'),
        ),
    ]
