# Generated by Django 4.1.4 on 2022-12-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_bot', '0006_alter_purchase_salon_alter_purchase_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='datetime',
            field=models.DateTimeField(null=True, verbose_name='Дата и время оказания услуги'),
        ),
    ]
