# Generated by Django 4.1.4 on 2022-12-09 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon_bot', '0008_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='salon_bot.user', verbose_name='Покупатель'),
        ),
    ]
