# Generated by Django 4.1.4 on 2022-12-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_bot', '0009_alter_purchase_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='services',
            field=models.ManyToManyField(related_name='salons', to='salon_bot.service', verbose_name='Услуги'),
        ),
    ]
