# Generated by Django 4.1.4 on 2022-12-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_bot', '0011_user_consent_of_personal_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=50, verbose_name='Обращение к клиенту'),
        ),
    ]
